#!/bin/bash

# DigiLocker Profile Endpoint Fix Script
# This script helps fix the 404 error by updating the Netlify environment variable

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 DigiLocker Profile Endpoint Fix"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ Problem: Profile fetch failed: 404 {}"
echo "   The /profile endpoint doesn't exist in DigiLocker API"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Step 1: Update Netlify Environment Variable"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://app.netlify.com"
echo "2. Select site: tenant-callviain"
echo "3. Go to: Site Settings → Environment Variables"
echo "4. Find: DIGILOCKER_PROFILE_ENDPOINT"
echo ""
echo "5. Change from:"
echo "   ❌ https://digilocker.meripehchaan.gov.in/public/oauth2/1/profile"
echo ""
echo "   To:"
echo "   ✅ https://digilocker.meripehchaan.gov.in/public/oauth2/3/user"
echo ""
echo "   (Try API v3 first, if that fails use v1: .../oauth2/1/user)"
echo ""
echo "6. Click 'Save'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Step 2: Trigger Deployment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After updating the environment variable, you need to"
echo "trigger a new deployment for it to take effect:"
echo ""
echo "Option A - From Terminal:"
read -p "Press Enter to trigger deploy via git push..." key
echo ""
echo "Running: git push origin main"
git push origin main
echo ""
echo "✅ Deploy triggered!"
echo ""
echo "Option B - From Netlify Dashboard:"
echo "  → Deploys → Trigger Deploy → Deploy site"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Step 3: Wait for Deploy (2-3 minutes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Monitor deploy at:"
echo "https://app.netlify.com/sites/tenant-callviain/deploys"
echo ""
read -p "Press Enter when deploy is complete..." key
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Step 4: Test KYC Flow"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open: https://tenants.callvia.in (incognito mode)"
echo "2. Login as a tenant"
echo "3. Click 'Verify with DigiLocker'"
echo "4. Complete authentication in popup"
echo "5. Check for ✅ Verified badge"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"  
echo "📋 Step 5: Check Logs (if issues persist)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "View function logs at:"
echo "https://app.netlify.com/sites/tenant-callviain/functions"
echo ""
echo "Look for these log lines:"
echo "  🔵 Fetching DigiLocker profile from: ..."
echo "  📡 Profile response status: 200  ← Should be 200, not 404"
echo "  📥 Profile payload received: {...}"
echo "  ✅ KYC verification successful"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Fix Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If you still see 404 errors:"
echo "  - Try API v1 endpoint: .../oauth2/1/user"
echo "  - Run endpoint tester: node scripts/test_digilocker_endpoints.js <token>"
echo "  - Check DIGILOCKER_PROFILE_404_FIX.md for more details"
echo ""
